-- MySQL Script generated by MySQL Workbench
-- Mon May 23 09:24:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema It_Company
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema It_Company
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `It_Company` DEFAULT CHARACTER SET utf8 ;
USE `It_Company` ;

-- -----------------------------------------------------
-- Table `It_Company`.`Sales_Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `It_Company`.`Sales_Area` (
  `id_Sales_Area` INT NOT NULL AUTO_INCREMENT,
  `sales_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Sales_Area`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `It_Company`.`Developers_Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `It_Company`.`Developers_Area` (
  `id_Developers_Team` INT NOT NULL AUTO_INCREMENT,
  `area_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Developers_Team`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `It_Company`.`Services_Provide`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `It_Company`.`Services_Provide` (
  `id_Services_Provide` INT NOT NULL AUTO_INCREMENT,
  `service_name` VARCHAR(45) NOT NULL,
  `Sales_Area_id_Sales_Area` INT NOT NULL,
  `Developers_Area_id_Developers_Team` INT NOT NULL,
  PRIMARY KEY (`id_Services_Provide`),
  INDEX `fk_Services_Provide_Sales_Area1_idx` (`Sales_Area_id_Sales_Area` ASC) VISIBLE,
  INDEX `fk_Services_Provide_Developers_Area1_idx` (`Developers_Area_id_Developers_Team` ASC) VISIBLE,
  CONSTRAINT `fk_Services_Provide_Sales_Area1`
    FOREIGN KEY (`Sales_Area_id_Sales_Area`)
    REFERENCES `It_Company`.`Sales_Area` (`id_Sales_Area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Services_Provide_Developers_Area1`
    FOREIGN KEY (`Developers_Area_id_Developers_Team`)
    REFERENCES `It_Company`.`Developers_Area` (`id_Developers_Team`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `It_Company`.`Custumers_Services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `It_Company`.`Custumers_Services` (
  `id_Custumers_Services` INT NOT NULL AUTO_INCREMENT,
  `case_number` VARCHAR(45) NOT NULL,
  `case_state` VARCHAR(45) NOT NULL,
  `lider_name` VARCHAR(45) NOT NULL,
  `start_date` DATE NOT NULL,
  PRIMARY KEY (`id_Custumers_Services`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `It_Company`.`UX_UI_Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `It_Company`.`UX_UI_Area` (
  `id_UX_UI_Team` INT NOT NULL AUTO_INCREMENT,
  `proyect_name` VARCHAR(45) NOT NULL,
  `Services_Provide_id_Services_Provide` INT NOT NULL,
  PRIMARY KEY (`id_UX_UI_Team`),
  INDEX `fk_UX_UI_Area_Services_Provide1_idx` (`Services_Provide_id_Services_Provide` ASC) VISIBLE,
  CONSTRAINT `fk_UX_UI_Area_Services_Provide1`
    FOREIGN KEY (`Services_Provide_id_Services_Provide`)
    REFERENCES `It_Company`.`Services_Provide` (`id_Services_Provide`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `It_Company`.`Custumers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `It_Company`.`Custumers` (
  `id_Custumers` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Custumers_Services_id_Custumers_Services` INT NOT NULL,
  `UX_UI_Area_id_UX_UI_Team` INT NOT NULL,
  `Developers_Area_id_Developers_Team` INT NOT NULL,
  PRIMARY KEY (`id_Custumers`),
  INDEX `fk_Custumers_Custumers_Services_idx` (`Custumers_Services_id_Custumers_Services` ASC) VISIBLE,
  INDEX `fk_Custumers_UX_UI_Area1_idx` (`UX_UI_Area_id_UX_UI_Team` ASC) VISIBLE,
  INDEX `fk_Custumers_Developers_Area1_idx` (`Developers_Area_id_Developers_Team` ASC) VISIBLE,
  CONSTRAINT `fk_Custumers_Custumers_Services`
    FOREIGN KEY (`Custumers_Services_id_Custumers_Services`)
    REFERENCES `It_Company`.`Custumers_Services` (`id_Custumers_Services`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Custumers_UX_UI_Area1`
    FOREIGN KEY (`UX_UI_Area_id_UX_UI_Team`)
    REFERENCES `It_Company`.`UX_UI_Area` (`id_UX_UI_Team`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Custumers_Developers_Area1`
    FOREIGN KEY (`Developers_Area_id_Developers_Team`)
    REFERENCES `It_Company`.`Developers_Area` (`id_Developers_Team`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `It_Company`.`RRHH_Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `It_Company`.`RRHH_Area` (
  `id_RRHH_Area` INT NOT NULL AUTO_INCREMENT,
  `employee_hollydays` INT NOT NULL,
  PRIMARY KEY (`id_RRHH_Area`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `It_Company`.`Purchasing_Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `It_Company`.`Purchasing_Area` (
  `id_Purchasing_Area` INT NOT NULL AUTO_INCREMENT,
  `order_number` INT NOT NULL,
  PRIMARY KEY (`id_Purchasing_Area`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `It_Company`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `It_Company`.`Employees` (
  `id_Employees` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `birth_date` DATE NOT NULL,
  `UX_UI_Area_id_UX_UI_Team` INT NOT NULL,
  `RRHH_Area_id_RRHH_Area` INT NOT NULL,
  `Purchasing_Area_id_Purchasing_Area` INT NOT NULL,
  `Sales_Area_id_Sales_Area` INT NOT NULL,
  PRIMARY KEY (`id_Employees`),
  INDEX `fk_Employees_UX_UI_Area1_idx` (`UX_UI_Area_id_UX_UI_Team` ASC) VISIBLE,
  INDEX `fk_Employees_RRHH_Area1_idx` (`RRHH_Area_id_RRHH_Area` ASC) VISIBLE,
  INDEX `fk_Employees_Purchasing_Area1_idx` (`Purchasing_Area_id_Purchasing_Area` ASC) VISIBLE,
  INDEX `fk_Employees_Sales_Area1_idx` (`Sales_Area_id_Sales_Area` ASC) VISIBLE,
  CONSTRAINT `fk_Employees_UX_UI_Area1`
    FOREIGN KEY (`UX_UI_Area_id_UX_UI_Team`)
    REFERENCES `It_Company`.`UX_UI_Area` (`id_UX_UI_Team`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employees_RRHH_Area1`
    FOREIGN KEY (`RRHH_Area_id_RRHH_Area`)
    REFERENCES `It_Company`.`RRHH_Area` (`id_RRHH_Area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employees_Purchasing_Area1`
    FOREIGN KEY (`Purchasing_Area_id_Purchasing_Area`)
    REFERENCES `It_Company`.`Purchasing_Area` (`id_Purchasing_Area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employees_Sales_Area1`
    FOREIGN KEY (`Sales_Area_id_Sales_Area`)
    REFERENCES `It_Company`.`Sales_Area` (`id_Sales_Area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `It_Company`.`Publicity_Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `It_Company`.`Publicity_Area` (
  `id_Publicity_Area` INT NOT NULL AUTO_INCREMENT,
  `budget` DOUBLE NOT NULL,
  `campaigns` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Publicity_Area`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `It_Company`.`Currents_Projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `It_Company`.`Currents_Projects` (
  `id_Currents_Projects` INT NOT NULL AUTO_INCREMENT,
  `proj_name` VARCHAR(45) NOT NULL,
  `star_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `UX_UI_Area_id_UX_UI_Team` INT NOT NULL,
  `Developers_Area_id_Developers_Team` INT NOT NULL,
  `Publicity_Area_id_Publicity_Area` INT NOT NULL,
  PRIMARY KEY (`id_Currents_Projects`),
  INDEX `fk_Currents_Projects_UX_UI_Area1_idx` (`UX_UI_Area_id_UX_UI_Team` ASC) VISIBLE,
  INDEX `fk_Currents_Projects_Developers_Area1_idx` (`Developers_Area_id_Developers_Team` ASC) VISIBLE,
  INDEX `fk_Currents_Projects_Publicity_Area1_idx` (`Publicity_Area_id_Publicity_Area` ASC) VISIBLE,
  CONSTRAINT `fk_Currents_Projects_UX_UI_Area1`
    FOREIGN KEY (`UX_UI_Area_id_UX_UI_Team`)
    REFERENCES `It_Company`.`UX_UI_Area` (`id_UX_UI_Team`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Currents_Projects_Developers_Area1`
    FOREIGN KEY (`Developers_Area_id_Developers_Team`)
    REFERENCES `It_Company`.`Developers_Area` (`id_Developers_Team`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Currents_Projects_Publicity_Area1`
    FOREIGN KEY (`Publicity_Area_id_Publicity_Area`)
    REFERENCES `It_Company`.`Publicity_Area` (`id_Publicity_Area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `It_Company`.`Finance_Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `It_Company`.`Finance_Area` (
  `id_Finance_Area` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Finance_Area`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `It_Company`.`Suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `It_Company`.`Suppliers` (
  `id_Suppliers` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Purchasing_Area_id_Purchasing_Area` INT NOT NULL,
  PRIMARY KEY (`id_Suppliers`),
  INDEX `fk_Suppliers_Purchasing_Area1_idx` (`Purchasing_Area_id_Purchasing_Area` ASC) VISIBLE,
  CONSTRAINT `fk_Suppliers_Purchasing_Area1`
    FOREIGN KEY (`Purchasing_Area_id_Purchasing_Area`)
    REFERENCES `It_Company`.`Purchasing_Area` (`id_Purchasing_Area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `It_Company`.`Salary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `It_Company`.`Salary` (
  `id_Salary` INT NOT NULL AUTO_INCREMENT,
  `amount` DOUBLE NOT NULL,
  `RRHH_Area_id_RRHH_Area` INT NOT NULL,
  PRIMARY KEY (`id_Salary`),
  INDEX `fk_Salary_RRHH_Area1_idx` (`RRHH_Area_id_RRHH_Area` ASC) VISIBLE,
  CONSTRAINT `fk_Salary_RRHH_Area1`
    FOREIGN KEY (`RRHH_Area_id_RRHH_Area`)
    REFERENCES `It_Company`.`RRHH_Area` (`id_RRHH_Area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `It_Company`.`Bills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `It_Company`.`Bills` (
  `idBills` INT NOT NULL,
  `bill_number` INT NOT NULL,
  `amount` DOUBLE NOT NULL,
  `Finance_Area_id_Finance_Area` INT NOT NULL,
  PRIMARY KEY (`idBills`),
  INDEX `fk_Bills_Finance_Area1_idx` (`Finance_Area_id_Finance_Area` ASC) VISIBLE,
  CONSTRAINT `fk_Bills_Finance_Area1`
    FOREIGN KEY (`Finance_Area_id_Finance_Area`)
    REFERENCES `It_Company`.`Finance_Area` (`id_Finance_Area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `It_Company`.`Bills_has_Custumers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `It_Company`.`Bills_has_Custumers` (
  `Bills_idBills` INT NOT NULL,
  `Custumers_id_Custumers` INT NOT NULL,
  PRIMARY KEY (`Bills_idBills`, `Custumers_id_Custumers`),
  INDEX `fk_Bills_has_Custumers_Custumers1_idx` (`Custumers_id_Custumers` ASC) VISIBLE,
  INDEX `fk_Bills_has_Custumers_Bills1_idx` (`Bills_idBills` ASC) VISIBLE,
  CONSTRAINT `fk_Bills_has_Custumers_Bills1`
    FOREIGN KEY (`Bills_idBills`)
    REFERENCES `It_Company`.`Bills` (`idBills`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bills_has_Custumers_Custumers1`
    FOREIGN KEY (`Custumers_id_Custumers`)
    REFERENCES `It_Company`.`Custumers` (`id_Custumers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
